=== danielbraga/XSeam2/XSeam/resources/domain/Domain.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="www.xseam.org/schemas/Domain" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="www.xseam.org/schemas/Domain">


    <xs:element name="domain" type="tns:item"></xs:element>

    <xs:complexType name="item">
    	<xs:sequence>
    		<xs:element name="domain" type="tns:domain" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="domain">
    	<xs:attribute name="id" type="xs:int" use="required"></xs:attribute>
    	<xs:attribute name="filter" type="xs:string" use="optional"></xs:attribute>
    	<xs:attribute name="description" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== danielbraga/XSeam2/XSeam/resources/domain/city/RJ.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="3300100" description="Angra do Reis" />
	<domain id="3300159" description="Aperibé" />
	<domain id="3300209" description="Araruama" />
	<domain id="3300225" description="Areal" />
	<domain id="3300233" description="Armação dos Búzios" />
	<domain id="3300258" description="Arraial do Cabo" />
	<domain id="3300308" description="Barra do Piraí" />
	<domain id="3300407" description="Barra Mansa" />
	<domain id="3300456" description="Belford Roxo" />
	<domain id="3300506" description="Bom Jardim" />
	<domain id="3300605" description="Bom Jesus do Itabapoana" />
	<domain id="3300704" description="Cabo Frio" />
	<domain id="3300803" description="Cachoeiras de Macacu" />
	<domain id="3300902" description="Cambuci" />
	<domain id="3301009" description="Campos dos Goytacazes" />
	<domain id="3301108" description="Cantagalo" />
	<domain id="3300936" description="Carapebus" />
	<domain id="3301157" description="Cardoso Moreira" />
	<domain id="3301207" description="Carmo" />
	<domain id="3301306" description="Casimiro de Abreu" />
	<domain id="3300951" description="Comendador Levy Gasparian" />
	<domain id="3301405" description="Conceição de Macabu" />
	<domain id="3301504" description="Cordeiro" />
	<domain id="3301603" description="Duas Barras" />
	<domain id="3301702" description="Duque de Caxias" />
	<domain id="3301801" description="Engenheiro Paulo de Frontin" />
	<domain id="3301850" description="Guapimirim" />
	<domain id="3301876" description="Iguaba Grande" />
	<domain id="3301900" description="Itaboraí" />
	<domain id="3302007" description="Itaguaí" />
	<domain id="3302056" description="Italva" />
	<domain id="3302106" description="Itaocara" />
	<domain id="3302205" description="Itaperuna" />
	<domain id="3302254" description="Itatiaia" />
	<domain id="3302270" description="Japeri" />
	<domain id="3302304" description="Laje do Muriaé" />
	<domain id="3302403" description="Macaé" />
	<domain id="3302452" description="Macuco" />
	<domain id="3302502" description="Magé" />
	<domain id="3302601" description="Mangaratiba" />
	<domain id="3302700" description="Maricá" />
	<domain id="3302809" description="Mendes" />
	<domain id="3302858" description="Mesquita" />
	<domain id="3302908" description="Miguel Pereira" />
	<domain id="3303005" description="Miracema" />
	<domain id="3303104" description="Natividade" />
	<domain id="3303203" description="Nilópolis" />
	<domain id="3303302" description="Niterói" />
	<domain id="3303401" description="Nova Friburgo" />
	<domain id="3303500" description="Nova Iguaçu" />
	<domain id="3303609" description="Paracambi" />
	<domain id="3303708" description="Paraíba do Sul" />
	<domain id="3303807" description="Parati" />
	<domain id="3303856" description="Paty do Alferes" />
	<domain id="3303906" description="Petrópolis" />
	<domain id="3303955" description="Pinheiral" />
	<domain id="3304003" description="Piraí" />
	<domain id="3304102" description="Porciúncula" />
	<domain id="3304110" description="Porto Real" />
	<domain id="3304128" description="Quatis" />
	<domain id="3304144" description="Queimados" />
	<domain id="3304151" description="Quissamã" />
	<domain id="3304201" description="Resende" />
	<domain id="3304300" description="Rio Bonito" />
	<domain id="3304409" description="Rio Claro" />
	<domain id="3304508" description="Rio das Flores" />
	<domain id="3304524" description="Rio das Ostras" />
	<domain id="3304557" description="Rio de Janeiro" />
	<domain id="3304607" description="Santa Maria Madalena" />
	<domain id="3304706" description="Santo Antônio de Pádua" />
	<domain id="3304805" description="São Fidélis" />
	<domain id="3304755" description="São Francisco de Itabapoana" />
	<domain id="3304904" description="São Gonçalo" />
	<domain id="3305000" description="São João da Barra" />
	<domain id="3305109" description="São João de Meriti" />
	<domain id="3305133" description="São José de Ubá" />
	<domain id="3305158" description="São José do Vale do Rio Preto" />
	<domain id="3305208" description="São Pedro da Aldeia" />
	<domain id="3305307" description="São Sebastião do Alto" />
	<domain id="3305406" description="Sapucaia" />
	<domain id="3305505" description="Saquarema" />
	<domain id="3305554" description="Seropédica" />
	<domain id="3305604" description="Silva Jardim" />
	<domain id="3305703" description="Sumidouro" />
	<domain id="3305752" description="Tanguá" />
	<domain id="3305802" description="Teresópolis" />
	<domain id="3305901" description="Trajano de Morais" />
	<domain id="3306008" description="Três Rios" />
	<domain id="3306107" description="Valença" />
	<domain id="3306156" description="Varre-Sai" />
	<domain id="3306206" description="Vassouras" />
	<domain id="3306305" description="Volta Redonda" />
</tns:domain>

=== danielbraga/XSeam2/XSeam/resources/domain/city/TO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="1700251" description="Abreulandia" />
	<domain id="1700301" description="Aguiarnópolis" />
	<domain id="1700350" description="Aliança do Tocantins" />
	<domain id="1700400" description="Almas" />
	<domain id="1700707" description="Alvorada" />
	<domain id="1701002" description="Ananás" />
	<domain id="1701051" description="Angico" />
	<domain id="1701101" description="Aparecida do Rio Negro" />
	<domain id="1701309" description="Aragominas" />
	<domain id="1701903" description="Araguacema" />
	<domain id="1702000" description="Araguaçu" />
	<domain id="1702109" description="Araguaína" />
	<domain id="1702158" description="Araguanã" />
	<domain id="1702208" description="Araguatins" />
	<domain id="1702307" description="Arapoema" />
	<domain id="1702406" description="Arraias" />
	<domain id="1702554" description="Augustinópolis" />
	<domain id="1702703" description="Aurora do Tocantins" />
	<domain id="1702901" description="Axixá do Tocantins" />
	<domain id="1703008" description="Babaçulândia" />
	<domain id="1703057" description="Bandeirantes do Tocantins" />
	<domain id="1703073" description="Barra do Ouro" />
	<domain id="1703107" description="Barrolândia" />
	<domain id="1703206" description="Bernardo Sayão" />
	<domain id="1703305" description="Bom Jesus do Tocantins" />
	<domain id="1703602" description="Brasilândia do Tocantins" />
	<domain id="1703701" description="Brejinho de Nazaré" />
	<domain id="1703800" description="Buriti do Tocantins" />
	<domain id="1703826" description="Cachoeirinha" />
	<domain id="1703842" description="Campos Lindos" />
	<domain id="1703867" description="Cariri do Tocantins" />
	<domain id="1703883" description="Carmolândia" />
	<domain id="1703891" description="Carrasco Bonito" />
	<domain id="1703909" description="Caseara" />
	<domain id="1704105" description="Centenário" />
	<domain id="1705102" description="Chapada da Natividade" />
	<domain id="1704600" description="Chapada de Areia" />
	<domain id="1705508" description="Colinas do Tocantins" />
	<domain id="1716703" description="Colméia" />
	<domain id="1705557" description="Combinado" />
	<domain id="1705607" description="Conceição do Tocantins" />
	<domain id="1706001" description="Couto de Magalhães" />
	<domain id="1706100" description="Cristalândia" />
	<domain id="1706258" description="Crixás do Tocantins" />
	<domain id="1706506" description="Darcinópolis" />
	<domain id="1707009" description="Dianópolis" />
	<domain id="1707108" description="Divinópolis do Tocantins" />
	<domain id="1707207" description="Dois Irmãos do Tocantins" />
	<domain id="1707306" description="Dueré" />
	<domain id="1707405" description="Esperantina" />
	<domain id="1707553" description="Fátima" />
	<domain id="1707652" description="Figueirópolis" />
	<domain id="1707702" description="Filadélfia" />
	<domain id="1708205" description="Formoso do Araguaia" />
	<domain id="1708254" description="Fortaleza do Tabocão" />
	<domain id="1708304" description="Goianorte" />
	<domain id="1709005" description="Goiatins" />
	<domain id="1709302" description="Guaraí" />
	<domain id="1709500" description="Gurupi" />
	<domain id="1709807" description="Ipueiras" />
	<domain id="1710508" description="Itacajá" />
	<domain id="1710706" description="Itaguatins" />
	<domain id="1710904" description="Itapiratins" />
	<domain id="1711100" description="Itaporã do Tocantins" />
	<domain id="1711506" description="Jaú do Tocantins" />
	<domain id="1711803" description="Juarina" />
	<domain id="1711902" description="Lagoa da Confusão" />
	<domain id="1711951" description="Lagoa do Tocantins" />
	<domain id="1712009" description="Lajeado" />
	<domain id="1712157" description="Lavandeira" />
	<domain id="1712405" description="Lizarda" />
	<domain id="1712454" description="Luzinópolis" />
	<domain id="1712504" description="Marianópolis do Tocantins" />
	<domain id="1712702" description="Mateiros" />
	<domain id="1712801" description="Maurilândia do Tocantins" />
	<domain id="1713205" description="Miracema do Tocantins" />
	<domain id="1713304" description="Miranorte" />
	<domain id="1713601" description="Monte do Carmo" />
	<domain id="1713700" description="Monte Santo do Tocantins" />
	<domain id="1713957" description="Muricilândia" />
	<domain id="1714203" description="Natividade" />
	<domain id="1714302" description="Nazaré" />
	<domain id="1714880" description="Nova Olinda" />
	<domain id="1715002" description="Nova Rosalândia" />
	<domain id="1715101" description="Novo Acordo" />
	<domain id="1715150" description="Novo Alegre" />
	<domain id="1715259" description="Novo Jardim" />
	<domain id="1715507" description="Oliveira de Fátima" />
	<domain id="1721000" description="Palmas" />
	<domain id="1715705" description="Palmeirante" />
	<domain id="1713809" description="Palmeiras do Tocantins" />
	<domain id="1715754" description="Palmeirópolis" />
	<domain id="1716109" description="Paraíso do Tocantins" />
	<domain id="1716208" description="Paranã" />
	<domain id="1716307" description="Pau D'Arco" />
	<domain id="1716505" description="Pedro Afonso" />
	<domain id="1716604" description="Peixe" />
	<domain id="1716653" description="Pequizeiro" />
	<domain id="1717008" description="Pindorama do Tocantins" />
	<domain id="1717206" description="Piraquê" />
	<domain id="1717503" description="Pium" />
	<domain id="1717800" description="Ponte Alta do Bom Jesus" />
	<domain id="1717909" description="Ponte Alta do Tocantins" />
	<domain id="1718006" description="Porto Alegre do Tocantins" />
	<domain id="1718204" description="Porto Nacional" />
	<domain id="1718303" description="Praia Norte" />
	<domain id="1718402" description="Presidente Kennedy" />
	<domain id="1718451" description="Pugmil" />
	<domain id="1718501" description="Recursolândia" />
	<domain id="1718550" description="Riachinho" />
	<domain id="1718659" description="Rio da Conceição" />
	<domain id="1718709" description="Rio dos Bois" />
	<domain id="1718758" description="Rio Sono" />
	<domain id="1718808" description="Sampaio" />
	<domain id="1718840" description="Sandolândia" />
	<domain id="1718865" description="Santa Fé do Araguaia" />
	<domain id="1718881" description="Santa Maria do Tocantins" />
	<domain id="1718899" description="Santa Rita do Tocantins" />
	<domain id="1718907" description="Santa Rosa do Tocantins" />
	<domain id="1719004" description="Santa Tereza do Tocantins" />
	<domain id="1720002" description="Santa Terezinha do Tocantins" />
	<domain id="1720101" description="São Bento do Tocantins" />
	<domain id="1720150" description="São Félix do Tocantins" />
	<domain id="1720200" description="São Miguel do Tocantins" />
	<domain id="1720259" description="São Salvador do Tocantins" />
	<domain id="1720309" description="São Sebastião do Tocantins" />
	<domain id="1720499" description="São Valério da Natividade" />
	<domain id="1720655" description="Silvanópolis" />
	<domain id="1720804" description="Sítio Novo do Tocantins" />
	<domain id="1720853" description="Sucupira" />
	<domain id="1720903" description="Taguatinga" />
	<domain id="1720937" description="Taipas do Tocantins" />
	<domain id="1720978" description="Talismã" />
	<domain id="1721109" description="Tocantínia" />
	<domain id="1721208" description="Tocantinópolis" />
	<domain id="1721257" description="Tupirama" />
	<domain id="1721307" description="Tupiratins" />
	<domain id="1722081" description="Wanderlândia" />
	<domain id="1722107" description="Xambioá" />
</tns:domain>

=== danielbraga/XSeam2/XSeam/resources/domain/city/PE.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="2600054" description="Abreu e Lima" />
	<domain id="2600104" description="Afogados da Ingazeira" />
	<domain id="2600203" description="Afrânio" />
	<domain id="2600302" description="Agrestina" />
	<domain id="2600401" description="Água Preta" />
	<domain id="2600500" description="Águas Belas" />
	<domain id="2600609" description="Alagoinha" />
	<domain id="2600708" description="Aliança" />
	<domain id="2600807" description="Altinho" />
	<domain id="2600906" description="Amaraji" />
	<domain id="2601003" description="Angelim" />
	<domain id="2601052" description="Araçoiaba" />
	<domain id="2601102" description="Araripina" />
	<domain id="2601201" description="Arcoverde" />
	<domain id="2601300" description="Barra de Guabiraba" />
	<domain id="2601409" description="Barreiros" />
	<domain id="2601508" description="Belém de Maria" />
	<domain id="2601607" description="Belém de São Francisco" />
	<domain id="2601706" description="Belo Jardim" />
	<domain id="2601805" description="Betânia" />
	<domain id="2601904" description="Bezerros" />
	<domain id="2602001" description="Bodocó" />
	<domain id="2602100" description="Bom Conselho" />
	<domain id="2602209" description="Bom Jardim" />
	<domain id="2602308" description="Bonito" />
	<domain id="2602407" description="Brejão" />
	<domain id="2602506" description="Brejinho" />
	<domain id="2602605" description="Brejo da Madre de Deus" />
	<domain id="2602704" description="Buenos Aires" />
	<domain id="2602803" description="Buíque" />
	<domain id="2602902" description="Cabo de Santo Agostinho" />
	<domain id="2603009" description="Cabrobó" />
	<domain id="2603108" description="Cachoeirinha" />
	<domain id="2603207" description="Caetés" />
	<domain id="2603306" description="Calçado" />
	<domain id="2603405" description="Calumbi" />
	<domain id="2603454" description="Camaragibe" />
	<domain id="2603504" description="Camocim de São Félix" />
	<domain id="2603603" description="Camutanga" />
	<domain id="2603702" description="Canhotinho" />
	<domain id="2603801" description="Capoeiras" />
	<domain id="2603900" description="Carnaíba" />
	<domain id="2603926" description="Carnaubeira da Penha" />
	<domain id="2604007" description="Carpina" />
	<domain id="2604106" description="Caruaru" />
	<domain id="2604155" description="Casinhas" />
	<domain id="2604205" description="Catende" />
	<domain id="2604304" description="Cedro" />
	<domain id="2604403" description="Chã de Alegria" />
	<domain id="2604502" description="Chã Grande" />
	<domain id="2604601" description="Condado" />
	<domain id="2604700" description="Correntes" />
	<domain id="2604809" description="Cortês" />
	<domain id="2604908" description="Cumaru" />
	<domain id="2605004" description="Cupira" />
	<domain id="2605103" description="Custódia" />
	<domain id="2605152" description="Dormentes" />
	<domain id="2605202" description="Escada" />
	<domain id="2605301" description="Exu" />
	<domain id="2605400" description="Feira Nova" />
	<domain id="2605459" description="Fernando de Noronha" />
	<domain id="2605509" description="Ferreiros" />
	<domain id="2605608" description="Flores" />
	<domain id="2605707" description="Floresta" />
	<domain id="2605806" description="Frei Miguelinho" />
	<domain id="2605905" description="Gameleira" />
	<domain id="2606002" description="Garanhuns" />
	<domain id="2606101" description="Glória do Goitá" />
	<domain id="2606200" description="Goiana" />
	<domain id="2606309" description="Granito" />
	<domain id="2606408" description="Gravatá" />
	<domain id="2606507" description="Iati" />
	<domain id="2606606" description="Ibimirim" />
	<domain id="2606705" description="Ibirajuba" />
	<domain id="2606804" description="Igarassu" />
	<domain id="2606903" description="Iguaraci" />
	<domain id="2607604" description="Ilha de Itamaracá" />
	<domain id="2607000" description="Inajá" />
	<domain id="2607109" description="Ingazeira" />
	<domain id="2607208" description="Ipojuca" />
	<domain id="2607307" description="Ipubi" />
	<domain id="2607406" description="Itacuruba" />
	<domain id="2607505" description="Itaíba" />
	<domain id="2607653" description="Itambé" />
	<domain id="2607703" description="Itapetim" />
	<domain id="2607752" description="Itapissuma" />
	<domain id="2607802" description="Itaquitinga" />
	<domain id="2607901" description="Jaboatão dos Guararapes" />
	<domain id="2607950" description="Jaqueira" />
	<domain id="2608008" description="Jataúba" />
	<domain id="2608057" description="Jatobá" />
	<domain id="2608107" description="João Alfredo" />
	<domain id="2608206" description="Joaquim Nabuco" />
	<domain id="2608255" description="Jucati" />
	<domain id="2608305" description="Jupi" />
	<domain id="2608404" description="Jurema" />
	<domain id="2608453" description="Lagoa do Carro" />
	<domain id="2608503" description="Lagoa do Itaenga" />
	<domain id="2608602" description="Lagoa do Ouro" />
	<domain id="2608701" description="Lagoa dos Gatos" />
	<domain id="2608750" description="Lagoa Grande" />
	<domain id="2608800" description="Lajedo" />
	<domain id="2608909" description="Limoeiro" />
	<domain id="2609006" description="Macaparana" />
	<domain id="2609105" description="Machados" />
	<domain id="2609154" description="Manari" />
	<domain id="2609204" description="Maraial" />
	<domain id="2609303" description="Mirandiba" />
	<domain id="2614303" description="Moreilândia" />
	<domain id="2609402" description="Moreno" />
	<domain id="2609501" description="Nazaré da Mata" />
	<domain id="2609600" description="Olinda" />
	<domain id="2609709" description="Orobó" />
	<domain id="2609808" description="Orocó" />
	<domain id="2609907" description="Ouricuri" />
	<domain id="2610004" description="Palmares" />
	<domain id="2610103" description="Palmeirina" />
	<domain id="2610202" description="Panelas" />
	<domain id="2610301" description="Paranatama" />
	<domain id="2610400" description="Parnamirim" />
	<domain id="2610509" description="Passira" />
	<domain id="2610608" description="Paudalho" />
	<domain id="2610707" description="Paulista" />
	<domain id="2610806" description="Pedra" />
	<domain id="2610905" description="Pesqueira" />
	<domain id="2611002" description="Petrolândia" />
	<domain id="2611101" description="Petrolina" />
	<domain id="2611200" description="Poção" />
	<domain id="2611309" description="Pombos" />
	<domain id="2611408" description="Primavera" />
	<domain id="2611507" description="Quipapá" />
	<domain id="2611533" description="Quixaba" />
	<domain id="2611606" description="Recife" />
	<domain id="2611705" description="Riacho das Almas" />
	<domain id="2611804" description="Ribeirão" />
	<domain id="2611903" description="Rio Formoso" />
	<domain id="2612000" description="Sairé" />
	<domain id="2612109" description="Salgadinho" />
	<domain id="2612208" description="Salgueiro" />
	<domain id="2612307" description="Saloá" />
	<domain id="2612406" description="Sanharó" />
	<domain id="2612455" description="Santa Cruz" />
	<domain id="2612471" description="Santa Cruz da Baixa Verde" />
	<domain id="2612505" description="Santa Cruz do Capibaribe" />
	<domain id="2612554" description="Santa Filomena" />
	<domain id="2612604" description="Santa Maria da Boa Vista" />
	<domain id="2612703" description="Santa Maria do Cambucá" />
	<domain id="2612802" description="Santa Terezinha" />
	<domain id="2612901" description="São Benedito do Sul" />
	<domain id="2613008" description="São Bento do Una" />
	<domain id="2613107" description="São Caitano" />
	<domain id="2613206" description="São João" />
	<domain id="2613305" description="São Joaquim do Monte" />
	<domain id="2613404" description="São José da Coroa Grande" />
	<domain id="2613503" description="São José do Belmonte" />
	<domain id="2613602" description="São José do Egito" />
	<domain id="2613701" description="São Lourenço da Mata" />
	<domain id="2613800" description="São Vicente Ferrer" />
	<domain id="2613909" description="Serra Talhada" />
	<domain id="2614006" description="Serrita" />
	<domain id="2614105" description="Sertânia" />
	<domain id="2614204" description="Sirinhaém" />
	<domain id="2614402" description="Solidão" />
	<domain id="2614501" description="Surubim" />
	<domain id="2614600" description="Tabira" />
	<domain id="2614709" description="Tacaimbó" />
	<domain id="2614808" description="Tacaratu" />
	<domain id="2614857" description="Tamandaré" />
	<domain id="2615003" description="Taquaritinga do Norte" />
	<domain id="2615102" description="Terezinha" />
	<domain id="2615201" description="Terra Nova" />
	<domain id="2615300" description="Timbaúba" />
	<domain id="2615409" description="Toritama" />
	<domain id="2615508" description="Tracunhaém" />
	<domain id="2615607" description="Trindade" />
	<domain id="2615706" description="Triunfo" />
	<domain id="2615805" description="Tupanatinga" />
	<domain id="2615904" description="Tuparetama" />
	<domain id="2616001" description="Venturosa" />
	<domain id="2616100" description="Verdejante" />
	<domain id="2616183" description="Vertente do Lério" />
	<domain id="2616209" description="Vertentes" />
	<domain id="2616308" description="Vicência" />
	<domain id="2616407" description="Vitória de Santo Antão" />
	<domain id="2616506" description="Xexéu" />
</tns:domain>

=== danielbraga/XSeam2/XSeam/resources/domain/city/AP.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="1600105" description="Amapa" />
	<domain id="1600204" description="Calçoene" />
	<domain id="1600212" description="Cutias" />
	<domain id="1600238" description="Ferreira Gomes" />
	<domain id="1600253" description="Itaubal" />
	<domain id="1600279" description="Laranjal do Jari" />
	<domain id="1600303" description="Macapá" />
	<domain id="1600402" description="Mazagão" />
	<domain id="1600501" description="Oiapoque" />
	<domain id="1600154" description="Pedra Branca do Amapari" />
	<domain id="1600535" description="Porto Grande" />
	<domain id="1600550" description="Pracuúba" />
	<domain id="1600600" description="Santana" />
	<domain id="1600055" description="Serra do Navio" />
	<domain id="1600709" description="Tartarugalzinho" />
	<domain id="1600808" description="Vitória do Jari" />
</tns:domain>

=== danielbraga/XSeam2/XSeam/resources/domain/city/AM.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="1300029" description="Alvaraes" />
	<domain id="1300060" description="Amaturá" />
	<domain id="1300086" description="Anamã" />
	<domain id="1300102" description="Anori" />
	<domain id="1300144" description="Apuí" />
	<domain id="1300201" description="Atalaia do Norte" />
	<domain id="1300300" description="Autazes" />
	<domain id="1300409" description="Barcelos" />
	<domain id="1300508" description="Barreirinha" />
	<domain id="1300607" description="Benjamin Constant" />
	<domain id="1300631" description="Beruri" />
	<domain id="1300680" description="Boa Vista do Ramos" />
	<domain id="1300706" description="Boca do Acre" />
	<domain id="1300805" description="Borba" />
	<domain id="1300839" description="Caapiranga" />
	<domain id="1300904" description="Canutama" />
	<domain id="1301001" description="Carauari" />
	<domain id="1301100" description="Careiro" />
	<domain id="1301159" description="Careiro da Várzea" />
	<domain id="1301209" description="Coari" />
	<domain id="1301308" description="Codajás" />
	<domain id="1301407" description="Eirunepé" />
	<domain id="1301506" description="Envira" />
	<domain id="1301605" description="Fonte Boa" />
	<domain id="1301654" description="Guajará" />
	<domain id="1301704" description="Humaitá" />
	<domain id="1301803" description="Ipixuna" />
	<domain id="1301852" description="Iranduba" />
	<domain id="1301902" description="Itacoatiara" />
	<domain id="1301951" description="Itamarati" />
	<domain id="1302009" description="Itapiranga" />
	<domain id="1302108" description="Japurá" />
	<domain id="1302207" description="Juruá" />
	<domain id="1302306" description="Jutaí" />
	<domain id="1302405" description="Lábrea" />
	<domain id="1302504" description="Manacapuru" />
	<domain id="1302553" description="Manaquiri" />
	<domain id="1302603" description="Manaus" />
	<domain id="1302702" description="Manicoré" />
	<domain id="1302801" description="Maraã" />
	<domain id="1302900" description="Maués" />
	<domain id="1303007" description="Nhamundá" />
	<domain id="1303106" description="Nova Olinda do Norte" />
	<domain id="1303205" description="Novo Airão" />
	<domain id="1303304" description="Novo Aripuanã" />
	<domain id="1303403" description="Parintins" />
	<domain id="1303502" description="Pauini" />
	<domain id="1303536" description="Presidente Figueiredo" />
	<domain id="1303569" description="Rio Preto da Eva" />
	<domain id="1303601" description="Santa Isabel do Rio Negro" />
	<domain id="1303700" description="Santo Antônio do Içá" />
	<domain id="1303809" description="São Gabriel da Cachoeira" />
	<domain id="1303908" description="São Paulo de Olivença" />
	<domain id="1303957" description="São Sebastião do Uatumã" />
	<domain id="1304005" description="Silves" />
	<domain id="1304062" description="Tabatinga" />
	<domain id="1304104" description="Tapauá" />
	<domain id="1304203" description="Tefé" />
	<domain id="1304237" description="Tonantins" />
	<domain id="1304260" description="Uarini" />
	<domain id="1304302" description="Urucará" />
	<domain id="1304401" description="Urucurituba" />
</tns:domain>

=== danielbraga/XSeam2/XSeam/resources/domain/state/brazil.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="12" description="AC" />
	<domain id="27" description="AL" />
	<domain id="13" description="AM" />
	<domain id="16" description="AP" />
	<domain id="29" description="BA" />
	<domain id="23" description="CE" />
	<domain id="53" description="DF" />
	<domain id="32" description="ES" />
	<domain id="52" description="GO" />
	<domain id="21" description="MA" />
	<domain id="31" description="MG" />
	<domain id="50" description="MS" />
	<domain id="51" description="MT" />
	<domain id="15" description="PA" />
	<domain id="25" description="PB" />
	<domain id="26" description="PE" />
	<domain id="22" description="PI" />
	<domain id="41" description="PR" />
	<domain id="33" description="RJ" />
	<domain id="24" description="RN" />
	<domain id="11" description="RO" />
	<domain id="14" description="RR" />
	<domain id="43" description="RS" />
	<domain id="42" description="SC" />
	<domain id="28" description="SE" />
	<domain id="35" description="SP" />
	<domain id="17" description="TO" />
</tns:domain>
