=== danielbraga/XSeam2/XSeam/resources/domain/Domain.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="www.xseam.org/schemas/Domain" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="www.xseam.org/schemas/Domain">


    <xs:element name="domain" type="tns:item"></xs:element>

    <xs:complexType name="item">
    	<xs:sequence>
    		<xs:element name="domain" type="tns:domain" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="domain">
    	<xs:attribute name="id" type="xs:int" use="required"></xs:attribute>
    	<xs:attribute name="filter" type="xs:string" use="optional"></xs:attribute>
    	<xs:attribute name="description" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== danielbraga/XSeam2/XSeam/resources/domain/city/PA.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="1500107" description="Abaetetuba" />
	<domain id="1500131" description="Abel Figueiredo" />
	<domain id="1500206" description="Acará" />
	<domain id="1500305" description="Afuá" />
	<domain id="1500347" description="Água Azul do Norte" />
	<domain id="1500404" description="Alenquer" />
	<domain id="1500503" description="Almeirim" />
	<domain id="1500602" description="Altamira" />
	<domain id="1500701" description="Anajás" />
	<domain id="1500800" description="Ananindeua" />
	<domain id="1500859" description="Anapu" />
	<domain id="1500909" description="Augusto Corrêa" />
	<domain id="1500958" description="Aurora do Pará" />
	<domain id="1501006" description="Aveiro" />
	<domain id="1501105" description="Bagre" />
	<domain id="1501204" description="Baião" />
	<domain id="1501253" description="Bannach" />
	<domain id="1501303" description="Barcarena" />
	<domain id="1501402" description="Belém" />
	<domain id="1501451" description="Belterra" />
	<domain id="1501501" description="Benevides" />
	<domain id="1501576" description="Bom Jesus do Tocantins" />
	<domain id="1501600" description="Bonito" />
	<domain id="1501709" description="Bragança" />
	<domain id="1501725" description="Brasil Novo" />
	<domain id="1501758" description="Brejo Grande do Araguaia" />
	<domain id="1501782" description="Breu Branco" />
	<domain id="1501808" description="Breves" />
	<domain id="1501907" description="Bujaru" />
	<domain id="1502004" description="Cachoeira do Arari" />
	<domain id="1501956" description="Cachoeira do Piriá" />
	<domain id="1502103" description="Cametá" />
	<domain id="1502152" description="Canaã dos Carajás" />
	<domain id="1502202" description="Capanema" />
	<domain id="1502301" description="Capitão Poço" />
	<domain id="1502400" description="Castanhal" />
	<domain id="1502509" description="Chaves" />
	<domain id="1502608" description="Colares" />
	<domain id="1502707" description="Conceição do Araguaia" />
	<domain id="1502756" description="Concórdia do Pará" />
	<domain id="1502764" description="Cumaru do Norte" />
	<domain id="1502772" description="Curionópolis" />
	<domain id="1502806" description="Curralinho" />
	<domain id="1502855" description="Curuá" />
	<domain id="1502905" description="Curuçá" />
	<domain id="1502939" description="Dom Eliseu" />
	<domain id="1502954" description="Eldorado dos Carajás" />
	<domain id="1503002" description="Faro" />
	<domain id="1503044" description="Floresta do Araguaia" />
	<domain id="1503077" description="Garrafão do Norte" />
	<domain id="1503093" description="Goianésia do Pará" />
	<domain id="1503101" description="Gurupá" />
	<domain id="1503200" description="Igarapé-Açu" />
	<domain id="1503309" description="Igarapé-Miri" />
	<domain id="1503408" description="Inhangapi" />
	<domain id="1503457" description="Ipixuna do Pará" />
	<domain id="1503507" description="Irituia" />
	<domain id="1503606" description="Itaituba" />
	<domain id="1503705" description="Itupiranga" />
	<domain id="1503754" description="Jacareacanga" />
	<domain id="1503804" description="Jacundá" />
	<domain id="1503903" description="Juruti" />
	<domain id="1504000" description="Limoeiro do Ajuru" />
	<domain id="1504059" description="Mãe do Rio" />
	<domain id="1504109" description="Magalhães Barata" />
	<domain id="1504208" description="Marabá" />
	<domain id="1504307" description="Maracanã" />
	<domain id="1504406" description="Marapanim" />
	<domain id="1504422" description="Marituba" />
	<domain id="1504455" description="Medicilândia" />
	<domain id="1504505" description="Melgaço" />
	<domain id="1504604" description="Mocajuba" />
	<domain id="1504703" description="Moju" />
	<domain id="1504802" description="Monte Alegre" />
	<domain id="1504901" description="Muaná" />
	<domain id="1504950" description="Nova Esperança do Piriá" />
	<domain id="1504976" description="Nova Ipixuna" />
	<domain id="1505007" description="Nova Timboteua" />
	<domain id="1505031" description="Novo Progresso" />
	<domain id="1505064" description="Novo Repartimento" />
	<domain id="1505106" description="Óbidos" />
	<domain id="1505205" description="Oeiras do Pará" />
	<domain id="1505304" description="Oriximiná" />
	<domain id="1505403" description="Ourém" />
	<domain id="1505437" description="Ourilândia do Norte" />
	<domain id="1505486" description="Pacajá" />
	<domain id="1505494" description="Palestina do Pará" />
	<domain id="1505502" description="Paragominas" />
	<domain id="1505536" description="Parauapebas" />
	<domain id="1505551" description="Pau D'Arco" />
	<domain id="1505601" description="Peixe-Boi" />
	<domain id="1505635" description="Piçarra" />
	<domain id="1505650" description="Placas" />
	<domain id="1505700" description="Ponta de Pedras" />
	<domain id="1505809" description="Portel" />
	<domain id="1505908" description="Porto de Moz" />
	<domain id="1506005" description="Prainha" />
	<domain id="1506104" description="Primavera" />
	<domain id="1506112" description="Quatipuru" />
	<domain id="1506138" description="Redenção" />
	<domain id="1506161" description="Rio Maria" />
	<domain id="1506187" description="Rondon do Pará" />
	<domain id="1506195" description="Rurópolis" />
	<domain id="1506203" description="Salinópolis" />
	<domain id="1506302" description="Salvaterra" />
	<domain id="1506351" description="Santa Bárbara do Pará" />
	<domain id="1506401" description="Santa Cruz do Arari" />
	<domain id="1506500" description="Santa Isabel do Pará" />
	<domain id="1506559" description="Santa Luzia do Pará" />
	<domain id="1506583" description="Santa Maria das Barreiras" />
	<domain id="1506609" description="Santa Maria do Pará" />
	<domain id="1506708" description="Santana do Araguaia" />
	<domain id="1506807" description="Santarém" />
	<domain id="1506906" description="Santarém Novo" />
	<domain id="1507003" description="Santo Antônio do Tauá" />
	<domain id="1507102" description="São Caetano de Odivelas" />
	<domain id="1507151" description="São Domingos do Araguaia" />
	<domain id="1507201" description="São Domingos do Capim" />
	<domain id="1507300" description="São Félix do Xingu" />
	<domain id="1507409" description="São Francisco do Pará" />
	<domain id="1507458" description="São Geraldo do Araguaia" />
	<domain id="1507466" description="São João da Ponta" />
	<domain id="1507474" description="São João de Pirabas" />
	<domain id="1507508" description="São João do Araguaia" />
	<domain id="1507607" description="São Miguel do Guamá" />
	<domain id="1507706" description="São Sebastião da Boa Vista" />
	<domain id="1507755" description="Sapucaia" />
	<domain id="1507805" description="Senador José Porfírio" />
	<domain id="1507904" description="Soure" />
	<domain id="1507953" description="Tailândia" />
	<domain id="1507961" description="Terra Alta" />
	<domain id="1507979" description="Terra Santa" />
	<domain id="1508001" description="Tomé-Açu" />
	<domain id="1508035" description="Tracuateua" />
	<domain id="1508050" description="Trairão" />
	<domain id="1508084" description="Tucumã" />
	<domain id="1508100" description="Tucuruí" />
	<domain id="1508126" description="Ulianópolis" />
	<domain id="1508159" description="Uruará" />
	<domain id="1508209" description="Vigia" />
	<domain id="1508308" description="Viseu" />
	<domain id="1508357" description="Vitória do Xingu" />
	<domain id="1508407" description="Xinguara" />
</tns:domain>

=== danielbraga/XSeam2/XSeam/resources/domain/city/SE.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="2800100" description="Amparo de São Francisco" />
	<domain id="2800209" description="Aquidabã" />
	<domain id="2800308" description="Aracaju" />
	<domain id="2800407" description="Arauá" />
	<domain id="2800506" description="Areia Branca" />
	<domain id="2800605" description="Barra dos Coqueiros" />
	<domain id="2800670" description="Boquim" />
	<domain id="2800704" description="Brejo Grande" />
	<domain id="2801009" description="Campo do Brito" />
	<domain id="2801108" description="Canhoba" />
	<domain id="2801207" description="Canindé de São Francisco" />
	<domain id="2801306" description="Capela" />
	<domain id="2801405" description="Carira" />
	<domain id="2801504" description="Carmópolis" />
	<domain id="2801603" description="Cedro de São João" />
	<domain id="2801702" description="Cristinápolis" />
	<domain id="2801900" description="Cumbe" />
	<domain id="2802007" description="Divina Pastora" />
	<domain id="2802106" description="Estância" />
	<domain id="2802205" description="Feira Nova" />
	<domain id="2802304" description="Frei Paulo" />
	<domain id="2802403" description="Gararu" />
	<domain id="2802502" description="General Maynard" />
	<domain id="2802601" description="Gracho Cardoso" />
	<domain id="2802700" description="Ilha das Flores" />
	<domain id="2802809" description="Indiaroba" />
	<domain id="2802908" description="Itabaiana" />
	<domain id="2803005" description="Itabaianinha" />
	<domain id="2803104" description="Itabi" />
	<domain id="2803203" description="Itaporanga d'Ajuda" />
	<domain id="2803302" description="Japaratuba" />
	<domain id="2803401" description="Japoatã" />
	<domain id="2803500" description="Lagarto" />
	<domain id="2803609" description="Laranjeiras" />
	<domain id="2803708" description="Macambira" />
	<domain id="2803807" description="Malhada dos Bois" />
	<domain id="2803906" description="Malhador" />
	<domain id="2804003" description="Maruim" />
	<domain id="2804102" description="Moita Bonita" />
	<domain id="2804201" description="Monte Alegre de Sergipe" />
	<domain id="2804300" description="Muribeca" />
	<domain id="2804409" description="Neópolis" />
	<domain id="2804458" description="Nossa Senhora Aparecida" />
	<domain id="2804508" description="Nossa Senhora da Glória" />
	<domain id="2804607" description="Nossa Senhora das Dores" />
	<domain id="2804706" description="Nossa Senhora de Lourdes" />
	<domain id="2804805" description="Nossa Senhora do Socorro" />
	<domain id="2804904" description="Pacatuba" />
	<domain id="2805000" description="Pedra Mole" />
	<domain id="2805109" description="Pedrinhas" />
	<domain id="2805208" description="Pinhão" />
	<domain id="2805307" description="Pirambu" />
	<domain id="2805406" description="Poço Redondo" />
	<domain id="2805505" description="Poço Verde" />
	<domain id="2805604" description="Porto da Folha" />
	<domain id="2805703" description="Propriá" />
	<domain id="2805802" description="Riachão do Dantas" />
	<domain id="2805901" description="Riachuelo" />
	<domain id="2806008" description="Ribeirópolis" />
	<domain id="2806107" description="Rosário do Catete" />
	<domain id="2806206" description="Salgado" />
	<domain id="2806305" description="Santa Luzia do Itanhy" />
	<domain id="2806503" description="Santa Rosa de Lima" />
	<domain id="2806404" description="Santana do São Francisco" />
	<domain id="2806602" description="Santo Amaro das Brotas" />
	<domain id="2806701" description="São Cristóvão" />
	<domain id="2806800" description="São Domingos" />
	<domain id="2806909" description="São Francisco" />
	<domain id="2807006" description="São Miguel do Aleixo" />
	<domain id="2807105" description="Simão Dias" />
	<domain id="2807204" description="Siriri" />
	<domain id="2807303" description="Telha" />
	<domain id="2807402" description="Tobias Barreto" />
	<domain id="2807501" description="Tomar do Geru" />
	<domain id="2807600" description="Umbaúba" />
</tns:domain>

=== danielbraga/XSeam2/XSeam/resources/domain/city/MS.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="5000203" description="Água Clara" />
	<domain id="5000252" description="Alcinópolis" />
	<domain id="5000609" description="Amambaí" />
	<domain id="5000708" description="Anastácio" />
	<domain id="5000807" description="Anaurilândia" />
	<domain id="5000856" description="Angélica" />
	<domain id="5000906" description="Antônio João" />
	<domain id="5001003" description="Aparecida do Taboado" />
	<domain id="5001102" description="Aquidauana" />
	<domain id="5001243" description="Aral Moreira" />
	<domain id="5001508" description="Bandeirantes" />
	<domain id="5001904" description="Bataguassu" />
	<domain id="5002001" description="Batayporã" />
	<domain id="5002100" description="Bela Vista" />
	<domain id="5002159" description="Bodoquena" />
	<domain id="5002209" description="Bonito" />
	<domain id="5002308" description="Brasilândia" />
	<domain id="5002407" description="Caarapó" />
	<domain id="5002605" description="Camapuã" />
	<domain id="5002704" description="Campo Grande" />
	<domain id="5002803" description="Caracol" />
	<domain id="5002902" description="Cassilândia" />
	<domain id="5002951" description="Chapadão do Sul" />
	<domain id="5003108" description="Corguinho" />
	<domain id="5003157" description="Coronel Sapucaia" />
	<domain id="5003207" description="Corumbá" />
	<domain id="5003256" description="Costa Rica" />
	<domain id="5003306" description="Coxim" />
	<domain id="5003454" description="Deodápolis" />
	<domain id="5003488" description="Dois Irmãos do Buriti" />
	<domain id="5003504" description="Douradina" />
	<domain id="5003702" description="Dourados" />
	<domain id="5003751" description="Eldorado" />
	<domain id="5003801" description="Fátima do Sul" />
	<domain id="5003900" description="Figueirão" />
	<domain id="5004007" description="Glória de Dourados" />
	<domain id="5004106" description="Guia Lopes da Laguna" />
	<domain id="5004304" description="Iguatemi" />
	<domain id="5004403" description="Inocência" />
	<domain id="5004502" description="Itaporã" />
	<domain id="5004601" description="Itaquiraí" />
	<domain id="5004700" description="Ivinhema" />
	<domain id="5004809" description="Japorã" />
	<domain id="5004908" description="Jaraguari" />
	<domain id="5005004" description="Jardim" />
	<domain id="5005103" description="Jateí" />
	<domain id="5005152" description="Juti" />
	<domain id="5005202" description="Ladário" />
	<domain id="5005251" description="Laguna Carapã" />
	<domain id="5005400" description="Maracaju" />
	<domain id="5005608" description="Miranda" />
	<domain id="5005681" description="Mundo Novo" />
	<domain id="5005707" description="Naviraí" />
	<domain id="5005806" description="Nioaque" />
	<domain id="5006002" description="Nova Alvorada do Sul" />
	<domain id="5006200" description="Nova Andradina" />
	<domain id="5006259" description="Novo Horizonte do Sul" />
	<domain id="5006309" description="Paranaíba" />
	<domain id="5006358" description="Paranhos" />
	<domain id="5006408" description="Pedro Gomes" />
	<domain id="5006606" description="Ponta Porã" />
	<domain id="5006903" description="Porto Murtinho" />
	<domain id="5007109" description="Ribas do Rio Pardo" />
	<domain id="5007208" description="Rio Brilhante" />
	<domain id="5007307" description="Rio Negro" />
	<domain id="5007406" description="Rio Verde de Mato Grosso" />
	<domain id="5007505" description="Rochedo" />
	<domain id="5007554" description="Santa Rita do Pardo" />
	<domain id="5007695" description="São Gabriel do Oeste" />
	<domain id="5007802" description="Selvíria" />
	<domain id="5007703" description="Sete Quedas" />
	<domain id="5007901" description="Sidrolândia" />
	<domain id="5007935" description="Sonora" />
	<domain id="5007950" description="Tacuru" />
	<domain id="5007976" description="Taquarussu" />
	<domain id="5008008" description="Terenos" />
	<domain id="5008305" description="Três Lagoas" />
	<domain id="5008404" description="Vicentina" />
</tns:domain>

=== danielbraga/XSeam2/XSeam/resources/domain/city/CE.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="2300101" description="Abaiara" />
	<domain id="2300150" description="Acarapé" />
	<domain id="2300200" description="Acaraú" />
	<domain id="2300309" description="Acopiara" />
	<domain id="2300408" description="Aiuaba" />
	<domain id="2300507" description="Alcântaras" />
	<domain id="2300606" description="Altaneira" />
	<domain id="2300705" description="Alto Santo" />
	<domain id="2300754" description="Amontada" />
	<domain id="2300804" description="Antonina do Norte" />
	<domain id="2300903" description="Apuiarés" />
	<domain id="2301000" description="Aquiraz" />
	<domain id="2301109" description="Aracati" />
	<domain id="2301208" description="Aracoiaba" />
	<domain id="2301257" description="Ararendá" />
	<domain id="2301307" description="Araripe" />
	<domain id="2301406" description="Aratuba" />
	<domain id="2301505" description="Arneiroz" />
	<domain id="2301604" description="Assaré" />
	<domain id="2301703" description="Aurora" />
	<domain id="2301802" description="Baixio" />
	<domain id="2301851" description="Banabuiú" />
	<domain id="2301901" description="Barbalha" />
	<domain id="2301950" description="Barreira" />
	<domain id="2302008" description="Barro" />
	<domain id="2302057" description="Barroquinha" />
	<domain id="2302107" description="Baturité" />
	<domain id="2302206" description="Beberibe" />
	<domain id="2302305" description="Bela Cruz" />
	<domain id="2302404" description="Boa Viagem" />
	<domain id="2302503" description="Brejo Santo" />
	<domain id="2302602" description="Camocim" />
	<domain id="2302701" description="Campos Sales" />
	<domain id="2302800" description="Canindé" />
	<domain id="2302909" description="Capistrano" />
	<domain id="2303006" description="Caridade" />
	<domain id="2303105" description="Cariré" />
	<domain id="2303204" description="Caririaçu" />
	<domain id="2303303" description="Cariús" />
	<domain id="2303402" description="Carnaubal" />
	<domain id="2303501" description="Cascavel" />
	<domain id="2303600" description="Catarina" />
	<domain id="2303659" description="Catunda" />
	<domain id="2303709" description="Caucaia" />
	<domain id="2303808" description="Cedro" />
	<domain id="2303907" description="Chaval" />
	<domain id="2303931" description="Choró" />
	<domain id="2303956" description="Chorozinho" />
	<domain id="2304004" description="Coreaú" />
	<domain id="2304103" description="Crateús" />
	<domain id="2304202" description="Crato" />
	<domain id="2304236" description="Croatá" />
	<domain id="2304251" description="Cruz" />
	<domain id="2304269" description="Deputado Irapuan Pinheiro" />
	<domain id="2304277" description="Ererê" />
	<domain id="2304285" description="Eusébio" />
	<domain id="2304301" description="Farias Brito" />
	<domain id="2304350" description="Forquilha" />
	<domain id="2304400" description="Fortaleza" />
	<domain id="2304459" description="Fortim" />
	<domain id="2304509" description="Frecheirinha" />
	<domain id="2304608" description="General Sampaio" />
	<domain id="2304657" description="Graça" />
	<domain id="2304707" description="Granja" />
	<domain id="2304806" description="Granjeiro" />
	<domain id="2304905" description="Groaíras" />
	<domain id="2304954" description="Guaiúba" />
	<domain id="2305001" description="Guaraciaba do Norte" />
	<domain id="2305100" description="Guaramiranga" />
	<domain id="2305209" description="Hidrolândia" />
	<domain id="2305233" description="Horizonte" />
	<domain id="2305266" description="Ibaretama" />
	<domain id="2305308" description="Ibiapina" />
	<domain id="2305332" description="Ibicuitinga" />
	<domain id="2305357" description="Icapuí" />
	<domain id="2305407" description="Icó" />
	<domain id="2305506" description="Iguatu" />
	<domain id="2305605" description="Independência" />
	<domain id="2305654" description="Ipaporanga" />
	<domain id="2305704" description="Ipaumirim" />
	<domain id="2305803" description="Ipu" />
	<domain id="2305902" description="Ipueiras" />
	<domain id="2306009" description="Iracema" />
	<domain id="2306108" description="Irauçuba" />
	<domain id="2306207" description="Itaiçaba" />
	<domain id="2306256" description="Itaitinga" />
	<domain id="2306306" description="Itapagé" />
	<domain id="2306405" description="Itapipoca" />
	<domain id="2306504" description="Itapiúna" />
	<domain id="2306553" description="Itarema" />
	<domain id="2306603" description="Itatira" />
	<domain id="2306702" description="Jaguaretama" />
	<domain id="2306801" description="Jaguaribara" />
	<domain id="2306900" description="Jaguaribe" />
	<domain id="2307007" description="Jaguaruana" />
	<domain id="2307106" description="Jardim" />
	<domain id="2307205" description="Jati" />
	<domain id="2307254" description="Jijoca de Jericoacoara" />
	<domain id="2307304" description="Juazeiro do Norte" />
	<domain id="2307403" description="Jucás" />
	<domain id="2307502" description="Lavras da Mangabeira" />
	<domain id="2307601" description="Limoeiro do Norte" />
	<domain id="2307635" description="Madalena" />
	<domain id="2307650" description="Maracanaú" />
	<domain id="2307700" description="Maranguape" />
	<domain id="2307809" description="Marco" />
	<domain id="2307908" description="Martinópole" />
	<domain id="2308005" description="Massapê" />
	<domain id="2308104" description="Mauriti" />
	<domain id="2308203" description="Meruoca" />
	<domain id="2308302" description="Milagres" />
	<domain id="2308351" description="Milhã" />
	<domain id="2308377" description="Miraíma" />
	<domain id="2308401" description="Missão Velha" />
	<domain id="2308500" description="Mombaça" />
	<domain id="2308609" description="Monsenhor Tabosa" />
	<domain id="2308708" description="Morada Nova" />
	<domain id="2308807" description="Moraújo" />
	<domain id="2308906" description="Morrinhos" />
	<domain id="2309003" description="Mucambo" />
	<domain id="2309102" description="Mulungu" />
	<domain id="2309201" description="Nova Olinda" />
	<domain id="2309300" description="Nova Russas" />
	<domain id="2309409" description="Novo Oriente" />
	<domain id="2309458" description="Ocara" />
	<domain id="2309508" description="Orós" />
	<domain id="2309607" description="Pacajus" />
	<domain id="2309706" description="Pacatuba" />
	<domain id="2309805" description="Pacoti" />
	<domain id="2309904" description="Pacujá" />
	<domain id="2310001" description="Palhano" />
	<domain id="2310100" description="Palmácia" />
	<domain id="2310209" description="Paracuru" />
	<domain id="2310258" description="Paraipaba" />
	<domain id="2310308" description="Parambu" />
	<domain id="2310407" description="Paramoti" />
	<domain id="2310506" description="Pedra Branca" />
	<domain id="2310605" description="Penaforte" />
	<domain id="2310704" description="Pentecoste" />
	<domain id="2310803" description="Pereiro" />
	<domain id="2310852" description="Pindoretama" />
	<domain id="2310902" description="Piquet Carneiro" />
	<domain id="2310951" description="Pires Ferreira" />
	<domain id="2311009" description="Poranga" />
	<domain id="2311108" description="Porteiras" />
	<domain id="2311207" description="Potengi" />
	<domain id="2311231" description="Potiretama" />
	<domain id="2311264" description="Quiterianópolis" />
	<domain id="2311306" description="Quixadá" />
	<domain id="2311355" description="Quixelô" />
	<domain id="2311405" description="Quixeramobim" />
	<domain id="2311504" description="Quixeré" />
	<domain id="2311603" description="Redenção" />
	<domain id="2311702" description="Reriutaba" />
	<domain id="2311801" description="Russas" />
	<domain id="2311900" description="Saboeiro" />
	<domain id="2311959" description="Salitre" />
	<domain id="2312205" description="Santa Quitéria" />
	<domain id="2312007" description="Santana do Acaraú" />
	<domain id="2312106" description="Santana do Cariri" />
	<domain id="2312304" description="São Benedito" />
	<domain id="2312403" description="São Gonçalo do Amarante" />
	<domain id="2312502" description="São João do Jaguaribe" />
	<domain id="2312601" description="São Luís do Curu" />
	<domain id="2312700" description="Senador Pompeu" />
	<domain id="2312809" description="Senador Sá" />
	<domain id="2312908" description="Sobral" />
	<domain id="2313005" description="Solonópole" />
	<domain id="2313104" description="Tabuleiro do Norte" />
	<domain id="2313203" description="Tamboril" />
	<domain id="2313252" description="Tarrafas" />
	<domain id="2313302" description="Tauá" />
	<domain id="2313351" description="Tejuçuoca" />
	<domain id="2313401" description="Tianguá" />
	<domain id="2313500" description="Trairi" />
	<domain id="2313559" description="Tururu" />
	<domain id="2313609" description="Ubajara" />
	<domain id="2313708" description="Umari" />
	<domain id="2313757" description="Umirim" />
	<domain id="2313807" description="Uruburetama" />
	<domain id="2313906" description="Uruoca" />
	<domain id="2313955" description="Varjota" />
	<domain id="2314003" description="Várzea Alegre" />
	<domain id="2314102" description="Viçosa do Ceará" />
</tns:domain>
