=== danielbraga/XSeam2/XSeam/resources/domain/Domain.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="www.xseam.org/schemas/Domain" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="www.xseam.org/schemas/Domain">


    <xs:element name="domain" type="tns:item"></xs:element>

    <xs:complexType name="item">
    	<xs:sequence>
    		<xs:element name="domain" type="tns:domain" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="domain">
    	<xs:attribute name="id" type="xs:int" use="required"></xs:attribute>
    	<xs:attribute name="filter" type="xs:string" use="optional"></xs:attribute>
    	<xs:attribute name="description" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== danielbraga/XSeam2/XSeam/resources/domain/city/MT.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="5100102" description="Acorizal" />
	<domain id="5100201" description="Água Boa" />
	<domain id="5100250" description="Alta Floresta" />
	<domain id="5100300" description="Alto Araguaia" />
	<domain id="5100359" description="Alto Boa Vista" />
	<domain id="5100409" description="Alto Garças" />
	<domain id="5100508" description="Alto Paraguai" />
	<domain id="5100607" description="Alto Taquari" />
	<domain id="5100805" description="Apiacás" />
	<domain id="5101001" description="Araguaiana" />
	<domain id="5101209" description="Araguainha" />
	<domain id="5101258" description="Araputanga" />
	<domain id="5101308" description="Arenápolis" />
	<domain id="5101407" description="Aripuanã" />
	<domain id="5101605" description="Barão de Melgaço" />
	<domain id="5101704" description="Barra do Bugres" />
	<domain id="5101803" description="Barra do Garças" />
	<domain id="5101852" description="Bom Jesus do Araguaia" />
	<domain id="5101902" description="Brasnorte" />
	<domain id="5102504" description="Cáceres" />
	<domain id="5102603" description="Campinápolis" />
	<domain id="5102637" description="Campo Novo do Parecis" />
	<domain id="5102678" description="Campo Verde" />
	<domain id="5102686" description="Campos de Júlio" />
	<domain id="5102694" description="Canabrava do Norte" />
	<domain id="5102702" description="Canarana" />
	<domain id="5102793" description="Carlinda" />
	<domain id="5102850" description="Castanheira" />
	<domain id="5103007" description="Chapada dos Guimarães" />
	<domain id="5103056" description="Cláudia" />
	<domain id="5103106" description="Cocalinho" />
	<domain id="5103205" description="Colíder" />
	<domain id="5103254" description="Colniza" />
	<domain id="5103304" description="Comodoro" />
	<domain id="5103353" description="Confresa" />
	<domain id="5103361" description="Conquista D'Oeste" />
	<domain id="5103379" description="Cotriguaçu" />
	<domain id="5103403" description="Cuiabá" />
	<domain id="5103437" description="Curvelândia" />
	<domain id="5103452" description="Denise" />
	<domain id="5103502" description="Diamantino" />
	<domain id="5103601" description="Dom Aquino" />
	<domain id="5103700" description="Feliz Natal" />
	<domain id="5103809" description="Figueirópolis D'Oeste" />
	<domain id="5103858" description="Gaúcha do Norte" />
	<domain id="5103908" description="General Carneiro" />
	<domain id="5103957" description="Glória D'Oeste" />
	<domain id="5104104" description="Guarantã do Norte" />
	<domain id="5104203" description="Guiratinga" />
	<domain id="5104500" description="Indiavaí" />
	<domain id="5104526" description="Ipiranga do Norte" />
	<domain id="5104542" description="Itanhanga" />
	<domain id="5104559" description="Itaúba" />
	<domain id="5104609" description="Itiquira" />
	<domain id="5104807" description="Jaciara" />
	<domain id="5104906" description="Jangada" />
	<domain id="5105002" description="Jauru" />
	<domain id="5105101" description="Juara" />
	<domain id="5105150" description="Juína" />
	<domain id="5105176" description="Juruena" />
	<domain id="5105200" description="Juscimeira" />
	<domain id="5105234" description="Lambari D'Oeste" />
	<domain id="5105259" description="Lucas do Rio Verde" />
	<domain id="5105309" description="Luciára" />
	<domain id="5105580" description="Marcelândia" />
	<domain id="5105606" description="Matupá" />
	<domain id="5105622" description="Mirassol d'Oeste" />
	<domain id="5105903" description="Nobres" />
	<domain id="5106000" description="Nortelândia" />
	<domain id="5106109" description="Nossa Senhora do Livramento" />
	<domain id="5106158" description="Nova Bandeirantes" />
	<domain id="5106208" description="Nova Brasilândia" />
	<domain id="5106216" description="Nova Canaã do Norte" />
	<domain id="5108808" description="Nova Guarita" />
	<domain id="5106182" description="Nova Lacerda" />
	<domain id="5108857" description="Nova Marilândia" />
	<domain id="5108907" description="Nova Maringá" />
	<domain id="5108956" description="Nova Monte Verde" />
	<domain id="5106224" description="Nova Mutum" />
	<domain id="5106174" description="Nova Nazaré" />
	<domain id="5106232" description="Nova Olímpia" />
	<domain id="5106190" description="Nova Santa Helena" />
	<domain id="5106240" description="Nova Ubiratã" />
	<domain id="5106257" description="Nova Xavantina" />
	<domain id="5106273" description="Novo Horizonte do Norte" />
	<domain id="5106265" description="Novo Mundo" />
	<domain id="5106315" description="Novo Santo Antônio" />
	<domain id="5106281" description="Novo São Joaquim" />
	<domain id="5106299" description="Paranaíta" />
	<domain id="5106307" description="Paranatinga" />
	<domain id="5106372" description="Pedra Preta" />
	<domain id="5106422" description="Peixoto de Azevedo" />
	<domain id="5106455" description="Planalto da Serra" />
	<domain id="5106505" description="Poconé" />
	<domain id="5106653" description="Pontal do Araguaia" />
	<domain id="5106703" description="Ponte Branca" />
	<domain id="5106752" description="Pontes e Lacerda" />
	<domain id="5106778" description="Porto Alegre do Norte" />
	<domain id="5106802" description="Porto dos Gaúchos" />
	<domain id="5106828" description="Porto Esperidião" />
	<domain id="5106851" description="Porto Estrela" />
	<domain id="5107008" description="Poxoréo" />
	<domain id="5107040" description="Primavera do Leste" />
	<domain id="5107065" description="Querência" />
	<domain id="5107156" description="Reserva do Cabaçal" />
	<domain id="5107180" description="Ribeirão Cascalheira" />
	<domain id="5107198" description="Ribeirãozinho" />
	<domain id="5107206" description="Rio Branco" />
	<domain id="5107578" description="Rondolândia" />
	<domain id="5107602" description="Rondonópolis" />
	<domain id="5107701" description="Rosário Oeste" />
	<domain id="5107750" description="Salto do Céu" />
	<domain id="5107248" description="Santa Carmem" />
	<domain id="5107743" description="Santa Cruz do Xingu" />
	<domain id="5107768" description="Santa Rita do Trivelato" />
	<domain id="5107776" description="Santa Terezinha" />
	<domain id="5107263" description="Santo Afonso" />
	<domain id="5107792" description="Santo Antônio do Leste" />
	<domain id="5107800" description="Santo Antônio do Leverger" />
	<domain id="5107859" description="São Félix do Araguaia" />
	<domain id="5107297" description="São José do Povo" />
	<domain id="5107305" description="São José do Rio Claro" />
	<domain id="5107354" description="São José do Xingu" />
	<domain id="5107107" description="São José dos Quatro Marcos" />
	<domain id="5107404" description="São Pedro da Cipa" />
	<domain id="5107875" description="Sapezal" />
	<domain id="5107883" description="Serra Nova Dourada" />
	<domain id="5107909" description="Sinop" />
	<domain id="5107925" description="Sorriso" />
	<domain id="5107941" description="Tabaporã" />
	<domain id="5107958" description="Tangará da Serra" />
	<domain id="5108006" description="Tapurah" />
	<domain id="5108055" description="Terra Nova do Norte" />
	<domain id="5108105" description="Tesouro" />
	<domain id="5108204" description="Torixoréu" />
	<domain id="5108303" description="União do Sul" />
	<domain id="5108352" description="Vale de São Domingos" />
	<domain id="5108402" description="Várzea Grande" />
	<domain id="5108501" description="Vera" />
	<domain id="5105507" description="Vila Bela da Santíssima Trindade" />
	<domain id="5108600" description="Vila Rica" />
</tns:domain>

=== danielbraga/XSeam2/XSeam/resources/domain/city/AL.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="2700102" description="Água Branca" />
	<domain id="2700201" description="Anadia" />
	<domain id="2700300" description="Arapiraca" />
	<domain id="2700409" description="Atalaia" />
	<domain id="2700508" description="Barra de Santo Antônio" />
	<domain id="2700607" description="Barra de São Miguel" />
	<domain id="2700706" description="Batalha" />
	<domain id="2700805" description="Belém" />
	<domain id="2700904" description="Belo Monte" />
	<domain id="2701001" description="Boca da Mata" />
	<domain id="2701100" description="Branquinha" />
	<domain id="2701209" description="Cacimbinhas" />
	<domain id="2701308" description="Cajueiro" />
	<domain id="2701357" description="Campestre" />
	<domain id="2701407" description="Campo Alegre" />
	<domain id="2701506" description="Campo Grande" />
	<domain id="2701605" description="Canapi" />
	<domain id="2701704" description="Capela" />
	<domain id="2701803" description="Carneiros" />
	<domain id="2701902" description="Chã Preta" />
	<domain id="2702009" description="Coité do Nóia" />
	<domain id="2702108" description="Colônia Leopoldina" />
	<domain id="2702207" description="Coqueiro Seco" />
	<domain id="2702306" description="Coruripe" />
	<domain id="2702355" description="Craíbas" />
	<domain id="2702405" description="Delmiro Gouveia" />
	<domain id="2702504" description="Dois Riachos" />
	<domain id="2702553" description="Estrela de Alagoas" />
	<domain id="2702603" description="Feira Grande" />
	<domain id="2702702" description="Feliz Deserto" />
	<domain id="2702801" description="Flexeiras" />
	<domain id="2702900" description="Girau do Ponciano" />
	<domain id="2703007" description="Ibateguara" />
	<domain id="2703106" description="Igaci" />
	<domain id="2703205" description="Igreja Nova" />
	<domain id="2703304" description="Inhapi" />
	<domain id="2703403" description="Jacaré dos Homens" />
	<domain id="2703502" description="Jacuípe" />
	<domain id="2703601" description="Japaratinga" />
	<domain id="2703700" description="Jaramataia" />
	<domain id="2703759" description="Jequiá da Praia" />
	<domain id="2703809" description="Joaquim Gomes" />
	<domain id="2703908" description="Jundiá" />
	<domain id="2704005" description="Junqueiro" />
	<domain id="2704104" description="Lagoa da Canoa" />
	<domain id="2704203" description="Limoeiro de Anadia" />
	<domain id="2704302" description="Maceió" />
	<domain id="2704401" description="Major Isdomainoro" />
	<domain id="2704906" description="Mar Vermelho" />
	<domain id="2704500" description="Maragogi" />
	<domain id="2704609" description="Maravilha" />
	<domain id="2704708" description="Marechal Deodoro" />
	<domain id="2704807" description="Maribondo" />
	<domain id="2705002" description="Mata Grande" />
	<domain id="2705101" description="Matriz de Camaragibe" />
	<domain id="2705200" description="Messias" />
	<domain id="2705309" description="Minador do Negrão" />
	<domain id="2705408" description="Monteirópolis" />
	<domain id="2705507" description="Murici" />
	<domain id="2705606" description="Novo Lino" />
	<domain id="2705705" description="Olho d'Água das Flores" />
	<domain id="2705804" description="Olho d'Água do Casado" />
	<domain id="2705903" description="Olho d'Água Grande" />
	<domain id="2706000" description="Olivença" />
	<domain id="2706109" description="Ouro Branco" />
	<domain id="2706208" description="Palestina" />
	<domain id="2706307" description="Palmeira dos Índios" />
	<domain id="2706406" description="Pão de Açúcar" />
	<domain id="2706422" description="Pariconha" />
	<domain id="2706448" description="Paripueira" />
	<domain id="2706505" description="Passo de Camaragibe" />
	<domain id="2706604" description="Paulo Jacinto" />
	<domain id="2706703" description="Penedo" />
	<domain id="2706802" description="Piaçabuçu" />
	<domain id="2706901" description="Pilar" />
	<domain id="2707008" description="Pindoba" />
	<domain id="2707107" description="Piranhas" />
	<domain id="2707206" description="Poço das Trincheiras" />
	<domain id="2707305" description="Porto Calvo" />
	<domain id="2707404" description="Porto de Pedras" />
	<domain id="2707503" description="Porto Real do Colégio" />
	<domain id="2707602" description="Quebrangulo" />
	<domain id="2707701" description="Rio Largo" />
	<domain id="2707800" description="Roteiro" />
	<domain id="2707909" description="Santa Luzia do Norte" />
	<domain id="2708006" description="Santana do Ipanema" />
	<domain id="2708105" description="Santana do Mundaú" />
	<domain id="2708204" description="São Brás" />
	<domain id="2708303" description="São José da Laje" />
	<domain id="2708402" description="São José da Tapera" />
	<domain id="2708501" description="São Luís do Quitunde" />
	<domain id="2708600" description="São Miguel dos Campos" />
	<domain id="2708709" description="São Miguel dos Milagres" />
	<domain id="2708808" description="São Sebastião" />
	<domain id="2708907" description="Satuba" />
	<domain id="2708956" description="Senador Rui Palmeira" />
	<domain id="2709004" description="Tanque d'Arca" />
	<domain id="2709103" description="Taquarana" />
	<domain id="2709152" description="Teotônio Vilela" />
	<domain id="2709202" description="Traipu" />
	<domain id="2709301" description="União dos Palmares" />
	<domain id="2709400" description="Viçosa" />
</tns:domain>

=== danielbraga/XSeam2/XSeam/resources/domain/city/RO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="1100015" description="Alta Floresta D´Oeste" />
	<domain id="1100379" description="Alto Alegre dos Parecis" />
	<domain id="1100403" description="Alto Paraíso" />
	<domain id="1100346" description="Alvorada D'Oeste" />
	<domain id="1100023" description="Ariquemes" />
	<domain id="1100452" description="Buritis" />
	<domain id="1100031" description="Cabixi" />
	<domain id="1100601" description="Cacaulândia" />
	<domain id="1100049" description="Cacoal" />
	<domain id="1100700" description="Campo Novo de Rondônia" />
	<domain id="1100809" description="Candeias do Jamari" />
	<domain id="1100908" description="Castanheiras" />
	<domain id="1100056" description="Cerejeiras" />
	<domain id="1100924" description="Chupinguaia" />
	<domain id="1100064" description="Colorado do Oeste" />
	<domain id="1100072" description="Corumbiara" />
	<domain id="1100080" description="Costa Marques" />
	<domain id="1100940" description="Cujubim" />
	<domain id="1100098" description="Espigão D'Oeste" />
	<domain id="1101005" description="Governador Jorge Teixeira" />
	<domain id="1100106" description="Guajará-Mirim" />
	<domain id="1101104" description="Itapuã do Oeste" />
	<domain id="1100114" description="Jaru" />
	<domain id="1100122" description="Ji-Paraná" />
	<domain id="1100130" description="Machadinho D'Oeste" />
	<domain id="1101203" description="Ministro Andreazza" />
	<domain id="1101302" description="Mirante da Serra" />
	<domain id="1101401" description="Monte Negro" />
	<domain id="1100148" description="Nova Brasilândia D'Oeste" />
	<domain id="1100338" description="Nova Mamoré" />
	<domain id="1101435" description="Nova União" />
	<domain id="1100502" description="Novo Horizonte do Oeste" />
	<domain id="1100155" description="Ouro Preto do Oeste" />
	<domain id="1101450" description="Parecis" />
	<domain id="1100189" description="Pimenta Bueno" />
	<domain id="1101468" description="Pimenteiras do Oeste" />
	<domain id="1100205" description="Porto Velho" />
	<domain id="1100254" description="Presidente Médici" />
	<domain id="1101476" description="Primavera de Rondônia" />
	<domain id="1100262" description="Rio Crespo" />
	<domain id="1100288" description="Rolim de Moura" />
	<domain id="1100296" description="Santa Luzia D'Oeste" />
	<domain id="1101484" description="São Felipe D'Oeste" />
	<domain id="1101492" description="São Francisco do Guaporé" />
	<domain id="1100320" description="São Miguel do Guaporé" />
	<domain id="1101500" description="Seringueiras" />
	<domain id="1101559" description="Teixeirópolis" />
	<domain id="1101609" description="Theobroma" />
	<domain id="1101708" description="Urupá" />
	<domain id="1101757" description="Vale do Anari" />
	<domain id="1101807" description="Vale do Paraíso" />
	<domain id="1100304" description="Vilhena" />
</tns:domain>

=== danielbraga/XSeam2/XSeam/resources/domain/city/RN.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:domain xmlns:tns="www.xseam.org/schemas/Domain"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="www.xseam.org/schemas/Domain ../Domain.xsd ">
	<domain id="2400109" description="Acari" />
	<domain id="2400208" description="Açu" />
	<domain id="2400307" description="Afonso Bezerra" />
	<domain id="2400406" description="Água Nova" />
	<domain id="2400505" description="Alexandria" />
	<domain id="2400604" description="Almino Afonso" />
	<domain id="2400703" description="Alto do Rodrigues" />
	<domain id="2400802" description="Angicos" />
	<domain id="2400901" description="Antônio Martins" />
	<domain id="2401008" description="Apodi" />
	<domain id="2401107" description="Areia Branca" />
	<domain id="2401206" description="Arês" />
	<domain id="2401305" description="Augusto Severo" />
	<domain id="2401404" description="Baía Formosa" />
	<domain id="2401453" description="Baraúna" />
	<domain id="2401503" description="Barcelona" />
	<domain id="2401602" description="Bento Fernandes" />
	<domain id="2401651" description="Bodó" />
	<domain id="2401701" description="Bom Jesus" />
	<domain id="2401800" description="Brejinho" />
	<domain id="2401859" description="Caiçara do Norte" />
	<domain id="2401909" description="Caiçara do Rio do Vento" />
	<domain id="2402006" description="Caicó" />
	<domain id="2402105" description="Campo Redondo" />
	<domain id="2402204" description="Canguaretama" />
	<domain id="2402303" description="Caraúbas" />
	<domain id="2402402" description="Carnaúba dos Dantas" />
	<domain id="2402501" description="Carnaubais" />
	<domain id="2402600" description="Ceará-Mirim" />
	<domain id="2402709" description="Cerro Corá" />
	<domain id="2402808" description="Coronel Ezequiel" />
	<domain id="2402907" description="Coronel João Pessoa" />
	<domain id="2403004" description="Cruzeta" />
	<domain id="2403103" description="Currais Novos" />
	<domain id="2403202" description="Doutor Severiano" />
	<domain id="2403301" description="Encanto" />
	<domain id="2403400" description="Equador" />
	<domain id="2403509" description="Espírito Santo" />
	<domain id="2403608" description="Extremoz" />
	<domain id="2403707" description="Felipe Guerra" />
	<domain id="2403756" description="Fernando Pedroza" />
	<domain id="2403806" description="Florânia" />
	<domain id="2403905" description="Francisco Dantas" />
	<domain id="2404002" description="Frutuoso Gomes" />
	<domain id="2404101" description="Galinhos" />
	<domain id="2404200" description="Goianinha" />
	<domain id="2404309" description="Governador Dix-Sept Rosado" />
	<domain id="2404408" description="Grossos" />
	<domain id="2404507" description="Guamaré" />
	<domain id="2404606" description="Ielmo Marinho" />
	<domain id="2404705" description="Ipanguaçu" />
	<domain id="2404804" description="Ipueira" />
	<domain id="2404853" description="Itajá" />
	<domain id="2404903" description="Itaú" />
	<domain id="2405009" description="Jaçanã" />
	<domain id="2405108" description="Jandaíra" />
	<domain id="2405207" description="Janduís" />
	<domain id="2405306" description="Januário Cicco" />
	<domain id="2405405" description="Japi" />
	<domain id="2405504" description="Jardim de Angicos" />
	<domain id="2405603" description="Jardim de Piranhas" />
	<domain id="2405702" description="Jardim do Seridó" />
	<domain id="2405801" description="João Câmara" />
	<domain id="2405900" description="João Dias" />
	<domain id="2406007" description="José da Penha" />
	<domain id="2406106" description="Jucurutu" />
	<domain id="2406155" description="Jundiá" />
	<domain id="2406205" description="Lagoa d'Anta" />
	<domain id="2406304" description="Lagoa de Pedras" />
	<domain id="2406403" description="Lagoa de Velhos" />
	<domain id="2406502" description="Lagoa Nova" />
	<domain id="2406601" description="Lagoa Salgada" />
	<domain id="2406700" description="Lajes" />
	<domain id="2406809" description="Lajes Pintadas" />
	<domain id="2406908" description="Lucrécia" />
	<domain id="2407005" description="Luís Gomes" />
	<domain id="2407104" description="Macaíba" />
	<domain id="2407203" description="Macau" />
	<domain id="2407252" description="Major Sales" />
	<domain id="2407302" description="Marcelino Vieira" />
	<domain id="2407401" description="Martins" />
	<domain id="2407500" description="Maxaranguape" />
	<domain id="2407609" description="Messias Targino" />
	<domain id="2407708" description="Montanhas" />
	<domain id="2407807" description="Monte Alegre" />
	<domain id="2407906" description="Monte das Gameleiras" />
	<domain id="2408003" description="Mossoró" />
	<domain id="2408102" description="Natal" />
	<domain id="2408201" description="Nísia Floresta" />
	<domain id="2408300" description="Nova Cruz" />
	<domain id="2408409" description="Olho-d'Água do Borges" />
	<domain id="2408508" description="Ouro Branco" />
	<domain id="2408607" description="Paraná" />
	<domain id="2408706" description="Paraú" />
	<domain id="2408805" description="Parazinho" />
	<domain id="2408904" description="Parelhas" />
	<domain id="2403251" description="Parnamirim" />
	<domain id="2409100" description="Passa e Fica" />
	<domain id="2409209" description="Passagem" />
	<domain id="2409308" description="Patu" />
	<domain id="2409407" description="Pau dos Ferros" />
	<domain id="2409506" description="Pedra Grande" />
	<domain id="2409605" description="Pedra Preta" />
	<domain id="2409704" description="Pedro Avelino" />
	<domain id="2409803" description="Pedro Velho" />
	<domain id="2409902" description="Pendências" />
	<domain id="2410009" description="Pilões" />
	<domain id="2410108" description="Poço Branco" />
	<domain id="2410207" description="Portalegre" />
	<domain id="2410256" description="Porto do Mangue" />
	<domain id="2410306" description="Presidente Juscelino" />
	<domain id="2410405" description="Pureza" />
	<domain id="2410504" description="Rafael Fernandes" />
	<domain id="2410603" description="Rafael Godeiro" />
	<domain id="2410702" description="Riacho da Cruz" />
	<domain id="2410801" description="Riacho de Santana" />
	<domain id="2410900" description="Riachuelo" />
	<domain id="2408953" description="Rio do Fogo" />
	<domain id="2411007" description="Rodolfo Fernandes" />
	<domain id="2411106" description="Ruy Barbosa" />
	<domain id="2411205" description="Santa Cruz" />
	<domain id="2409332" description="Santa Maria" />
	<domain id="2411403" description="Santana do Matos" />
	<domain id="2411429" description="Santana do Seridó" />
	<domain id="2411502" description="Santo Antônio" />
	<domain id="2411601" description="São Bento do Norte" />
	<domain id="2411700" description="São Bento do Trairí" />
	<domain id="2411809" description="São Fernando" />
	<domain id="2411908" description="São Francisco do Oeste" />
	<domain id="2412005" description="São Gonçalo do Amarante" />
	<domain id="2412104" description="São João do Sabugi" />
	<domain id="2412203" description="São José de Mipibu" />
	<domain id="2412302" description="São José do Campestre" />
	<domain id="2412401" description="São José do Seridó" />
	<domain id="2412500" description="São Miguel" />
	<domain id="2412559" description="São Miguel do Gostoso" />
	<domain id="2412609" description="São Paulo do Potengi" />
	<domain id="2412708" description="São Pedro" />
	<domain id="2412807" description="São Rafael" />
	<domain id="2412906" description="São Tomé" />
	<domain id="2413003" description="São Vicente" />
	<domain id="2413102" description="Senador Elói de Souza" />
	<domain id="2413201" description="Senador Georgino Avelino" />
	<domain id="2413300" description="Serra de São Bento" />
	<domain id="2413359" description="Serra do Mel" />
	<domain id="2413409" description="Serra Negra do Norte" />
	<domain id="2413508" description="Serrinha" />
	<domain id="2413557" description="Serrinha dos Pintos" />
	<domain id="2413607" description="Severiano Melo" />
	<domain id="2413706" description="Sítio Novo" />
	<domain id="2413805" description="Taboleiro Grande" />
	<domain id="2413904" description="Taipu" />
	<domain id="2414001" description="Tangará" />
	<domain id="2414100" description="Tenente Ananias" />
	<domain id="2414159" description="Tenente Laurentino Cruz" />
	<domain id="2411056" description="Tibau" />
	<domain id="2414209" description="Tibau do Sul" />
	<domain id="2414308" description="Timbaúba dos Batistas" />
	<domain id="2414407" description="Touros" />
	<domain id="2414456" description="Triunfo Potiguar" />
	<domain id="2414506" description="Umarizal" />
	<domain id="2414605" description="Upanema" />
	<domain id="2414704" description="Várzea" />
	<domain id="2414753" description="Venha-Ver" />
	<domain id="2414803" description="Vera Cruz" />
	<domain id="2414902" description="Viçosa" />
	<domain id="2415008" description="Vila Flor" />
</tns:domain>
